### ISSUE TITLE
Command-line inputs: bad parsing?

### ISSUE THREAD

**Issue by a3n** [mirage/mirage-solo5#33]
While checking the documentation of MirageOS, more precisely the tutorial [Hello MirageOS World](https://mirage.io/wiki/hello-world), at the end of Step 1,  I encountered an unexpected behaviour of the command-line parsing for the Solo5 backend.
Namely, if I do:
`mirage configure -t hvt`
`make depend`
`make`
`./solo5-hvt -- hello.hvt --hello="simple test"`,
then I get the following error message:
[...]
`hello: too many arguments, don't know what to do with "test"`
[...].
It seems to be the cases for all inputs containing at least one white space.
However, it is not the case when I execute the equivalent commands for a Unix backend.
Moreover, it is not the case if the input is set as default value:
`mirage configure -t hvt --hello="simple test"`,
then everything works fine.
I am using opam 2.0.0, mirage 3.2.0, mirage-solo5 0.4.0.

**Comment by mato** [comment]
Copying from solo5/solo5#281, different manifestation of the same underlying parser:

>If the unikernel boot parameter values contain double quotes (") they correctly end up in the Key_gen module if it is compiled for the unix target. In the hvt case the quotes get lost and must be escaped with an addition backspace (\"). In any case I believe it should be consistent and behave in the same way for unix and hvt targets.

In the Solo5 case, the code that is responsible for this gets the command line as a single string (unlike unix, not an `argv[]`). This then, via https://github.com/mirage/mirage-bootvar-solo5/blob/824796885d7354a7740a71d58438f076c3cdab3b/lib/bootvar.ml#L19 calls out to `Parse_argv.parse`, which lives in https://github.com/mirage/parse-argv and is also used by the Xen target.

Unfortunately we cannot change the behaviour where the command line is passed in from the tender (or Xen) as a single string. So, either `Parse_argv` can be improved in some way, or we just need to document the differences in behaviour.

**Comment by ansiwen** [comment]
So, the information obviously gets lost, when the argv strings are merged into a single string without escaping, which one could consider as a bug. As it seems like Parse_argv parses a whitespace separated list of optionally quoted strings, why not taking the argv strings, escaping the contained quotes, wrapping them in quotes and join them with a space when generating the single string?

**Comment by mato** [comment]
On Tuesday, 09.10.2018 at 03:32, Sven Anderson wrote:
> So, the information obviously gets lost, when the argv strings are merged into a single string without escaping, which one could consider as a bug. As it seems like Parse_argv parses a whitespace separated list of optionally quoted strings, why not taking the argv strings, escaping the contained quotes, wrapping them in quotes and join them with a space when generating the single string?

You mean on the Solo5 (tender) side? That would require doing more parsing
in C, which I'm not happy about.

**Comment by ansiwen** [comment]
I can feel your reluctance to do that in C, but if the code that throws away the information is written in C, I don't see another way to fix it. Otherwise the information is lost. And escaping certain characters in strings should be so common, that we can probably find well-cured code in C that does that.

**Comment by mato** [comment]
Just discussed this with @hannesm, the best way forward right now is to make the `unix` target also use `Parse_argv` instead of just `OS.Env.argv` directly. That way we get _consistent_ behaviour for all targets, and we can document that behaviour, _and_ we don't need any parsing code in C on the Solo5 side.

**Comment by hannesm** [comment]
@a3n from your referenced website, I could only find `$ ./solo5-hvt -- hello.hvt --hello="Hola!"` which works as expected for me.

I agree that the behaviour between the targets (on Unix, `./hello --hello="foo bar"` works, while it doesn't with solo5-hvt) is unfortunate. I prepared a fix https://github.com/mirage/mirage/pull/931 which adjusts the unix behaviour to the same as other targets. We should document the `parse-argv` somewhere.

@mato I am as well not happy with complex C parsing code.

**Comment by hannesm** [comment]
> you think searching for the " character and replacing it with \" is too complex to implement it in C

yes.  you would have to handle `"` when inside `'` or `"`, or prefixed by `\"` - this would require a huge amount of complexity (same as bash command line parsing etc.) for no obvious benefit, plus there'll be need to make the xen bootvar consistent with this.

> the other behavior is counter-intuitive for most people

as I mentioned in the issue on mirage/mirage, we need to document the boot parameter (parse_argv), and that should be fine then.

> it seems to me to be a well confined small problem, that can safely be implemented in C. I also volunteer to write it, if that should be the issue.

String parsing in C is complex and hard to write in my opinion. If you come up with less then 3 lines of C code (without any dynamic allocation etc.) to do the escaping, and an exhaustive test suite against different mirage targets, I'm happy to re-think my current opinion.

**Comment by hannesm** [comment]
on a further note: `./solo5-hvt -- hello.hvt '--hello="foo bar"'` -- having single quotes around the complete argument -- works well (and once the mirage-bootvar-unix is used behaves consistently across backends).

**Comment by ansiwen** [comment]
> > you think searching for the " character and replacing it with " is too complex to implement it in C
> 
> yes. you would have to handle `"` when inside `'` or `"`, or prefixed by `\"` - this would require a huge amount of complexity (same as bash command line parsing etc.) for no obvious benefit, plus there'll be need to make the xen bootvar consistent with this.

Why would we have to? If I look at Parse_argv code, I only see handling of `"` and `\`. IIUC, to let Parse_argv.parse resemble an array of strings that is identical to the original argv array, it is enough to replace `"` and `\` with `\"` and `\\` respectively, wrap it in `"` and join them with spaces. I implemented this and I didn't find any problems. Can you give a problematic example that would not be correctly handled by that?
 
> > the other behavior is counter-intuitive for most people
> 
> as I mentioned in the issue on mirage/mirage, we need to document the boot parameter (parse_argv), and that should be fine then.

I will give you a real life example, why it is indeed cumbersome to use IMHO. I have a unikernel that takes JSON strings as boot parameters. With the current implementation of solo5, I have to write

```
$ ./solo5-hvt --net=tap100 ./unikernel --json '"{\"foo\": \"bar\"}"'
```
or &ndash; if I can't use `'` because I want to expand variables &ndash; I even have to write
```
$ ./solo5-hvt --net=tap100 ./unikernel --json "\"{\\\"foo\\\": \\\"$BAR\\\"}\""
```
which... come on... looks horrible, or &ndash; if I want to read it from a file &ndash;
```
$ ./solo5-hvt --net=tap100 ./unikernel --json $(cat my.json | sed 's/\(["\]\)/\\\1/g')
```

With correct escaping within the solo5 tender I can just write
```
$ ./solo5-hvt --net=tap100 ./unikernel --json '{"foo": "bar"}'
$ ./solo5-hvt --net=tap100 ./unikernel --json "{\"foo\": \"$BAR\"}"
$ ./solo5-hvt --net=tap100 ./unikernel --json $(cat my.json)
```
which is so much more what one would expect.

> > it seems to me to be a well confined small problem, that can safely be implemented in C. I also volunteer to write it, if that should be the issue.
> 
> String parsing in C is complex and hard to write in my opinion. If you come up with less then 3 lines of C code (without any dynamic allocation etc.) to do the escaping, and an exhaustive test suite against different mirage targets, I'm happy to re-think my current opinion.

In general you are right of course, but I still have the understanding that in this case only trivial replacement of two characters and wrapping is required. 2 lines of code is a bit too ambitious, but I managed to write it with only 4 additional lines (not counting empty lines). Please have a look at the code in #283, and if you guys are fine with it in general, I'm happy to add tests as well. ;-)

**Comment by ansiwen** [comment]
I just realized, that I don't have to quote the strings, since also the space character can be escaped. That further simplified the code and I'm indeed down to two additional lines now. 😜 (Not that I would say number of lines is more important than readability, but I was surprised that it's actually possible.)

**Comment by hannesm** [comment]
as already expressed: I value uniformity between targets very high, and I'm not fond of adding any additional line of C code. From what I read, there's no way on Xen to retrieve an `argv vector` instead of cmdline (via xenstore's `/vm/UUID/image/cmdline` as done in mirage-bootvar-xen via start_info page), also unclear to me whether virtio would provide this functionality (atm it uses mutliboot struct and cmdline in there).

Please see https://github.com/mirage/mirage/pull/931 for my proposal, adapting the current behaviour of hvt/virtio/xen to unix, which unifies the behaviour across all backends!

This will be my last comment here since there's really nothing more to add from my side; I don't see how to get uniformity across targets unless patching up xen toolchain, and virtio.

**Comment by ansiwen** [comment]
@hannesm: In favor of usability I wouldn't have a problem with separate uniformity among the argv based launchers (unix, hvt), and among the launchers that only use a single string for all unikernel parameters (virtio, xen) where we have no other choice. It is anyway not strictly uniform, because in the latter case you have to wrap all parameters in `"` or escape the spaces.

However, assuming @mato agrees with you here, I extended the Parse_argv module with a single quote handling, that allows at least to write my examples from above like:
```
$ ./solo5-hvt --net=tap100 ./unikernel --json \''{"foo": "bar"}'\'
$ ./solo5-hvt --net=tap100 ./unikernel --json \''{"foo": '$BAR'}'\'
$ ./solo5-hvt --net=tap100 ./unikernel --json \'$(cat my.json)\'
```
See mirage/parse-argv#6

**Comment by mato** [comment]
I agree with @hannesm, and I also do not want more C parsing code in Solo5 if that job can be done elsewhere. So, I'm closing #283. Regarding the exact semantics of mirage/parse-argv#6, we can discuss those there.

**Comment by hannesm** [comment]
This is further discussed in https://github.com/mirage/parse-argv/pull/6 and not mirage-solo5 specific (but rather mirage-specific). Since MirageOS 3.3.0 (recently released), all targets go through the `parse-argv` library, and handle command line arguments uniformly. Our documentation (on mirage.io) and examples (e.g. the mirage/mirage-skeleton repository) were checked to work with MirageOS 3.3.0 - please let us know if there is documentation that won't work out of the box.
