### ISSUE TITLE
Port Mirage/Solo5 packages to Dune

### ISSUE THREAD

**Issue by g2p** [mirage/mirage-solo5#41]
This concerns the following packages:
- [x] mirage-block-solo5
- [x] mirage-bootvar-solo5
- [x] mirage-console-solo5
- [x] mirage-net-solo5
- [x] mirage-solo5 (@hannesm #58)

Notably, ocaml-freestanding and Solo5 itself (solo5-bindings-*) are not in scope here as these use a Makefile-based build system and Solo5 itself should not _depend_ on any OCaml tooling.

----

This will allow easier iteration (starting with vendoring) on barriers and discard which Wodan needs.

@pascutto has already ported mirage-block-solo5.
As @mato points out, we should keep a single build system for Solo5, so port the other device packages as well as mirage-solo5 itself.

**Comment by mato** [comment]
Updated the description and title to better reflect the scope as the original title was confusing.

@g2p: For the device driver packages (block, bootvar, console, net) this should be fairly straightforward. I would start there.

For mirage-solo5 itself, be aware that:
- the package needs to build a **static** clib out of these [sources](https://github.com/mirage/mirage-solo5/blob/master/lib/libmirage-solo5_bindings.clib), and do so using the CFLAGS etc coming from ocaml-freestanding (see _tags). This is what the `ocamlmklib -custom` (stupidest name ever for `-static`) invocation in myocamlbuild.ml does.
- further, the package needs to install a .pc file for downstream use (so that unikernels link against the clib)
- see pkg/pkg.ml and myocamlbuild.ml for how this is currently done

**Comment by mato** [comment]
> the package needs to build a static clib

To clarify what I mean by this: The build product needs to be a `.a` containing those objects. Ocamlbuild has a tendency to try and automatically build a `.so`, that needs to be disabled. The object files _themselves_ _may_ be compiled with `-fPIC` if the solo5-bindings-X requests that, which it does for Genode for example.

**Comment by mato** [comment]
All done here thanks to @hannesm work in #58. Will be in the next release.
